"""
Column-generation variant of the ILP source placement model.

This module does not replace ilp_multipartite_source_placement.py. It adds a
scalable workflow:

    1. Build a small initial candidate-tree set.
    2. Solve the LP-relaxed restricted master problem (RMP).
    3. Use dual variables to price new multipartite Steiner-like trees. The
       default pricing mode is exact over a finite candidate pool generated by
       the same mechanism as the full ILP.
    4. Repeat until no positive reduced-profit tree is found.
    5. Solve the final integer master problem over generated columns.

The final output is still a source placement. The master problems maximize an
expected per-slot throughput surrogate based on the same physical
probabilities as the simulator; entanglement routing, swapping, and fusion are
sampled afterwards by the stochastic simulator.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

import networkx as nx

try:
    import gurobipy as gp
    from gurobipy import GRB
except ImportError as exc:
    raise ImportError(
        "gurobipy is required for the column generation ILP module."
    ) from exc

from ilp_multipartite_source_placement import (
    GUROBI_SEED_MAX,
    CandidateTree,
    MultipartiteRequest,
    build_candidate_trees_for_requests,
    compute_tree_memory,
    ilp_objective_mode,
    norm_edge,
    requests_from_user_sets,
    served_request_priority,
    solve_joint_source_placement_ilp,
    status_to_string,
    tree_expected_throughput_value,
)
from network_topology import Topology
from seed_utils import derive_seed, set_global_seed
from steiner_tree_algorithms import approximate_steiner_tree
from tree_operation_planner import build_tree_operation_plan


Edge = Tuple[Any, Any]


@dataclass
class RMPResult:
    status: int
    status_name: str
    objective: float
    request_duals: Dict[int, float]
    request_lower_duals: Dict[int, float]
    request_upper_duals: Dict[int, float]
    edge_duals: Dict[Edge, float]
    edge_exact_duals: Dict[Edge, float]
    budget_dual: float
    memory_duals: Dict[Any, float]
    source_memory_duals: Dict[Any, float]
    objective_mode: str
    model: Any


@dataclass
class PricingResult:
    request_id: int
    candidate: Optional[CandidateTree]
    reduced_profit: float
    added: bool


def tree_signature(tree: nx.Graph) -> frozenset:
    return frozenset(norm_edge(u, v) for u, v in tree.edges())


def next_tree_id(candidate_trees: Dict[int, List[CandidateTree]]) -> int:
    max_id = -1
    for trees in candidate_trees.values():
        for tree in trees:
            max_id = max(max_id, tree.tree_id)
    return max_id + 1


def candidate_from_tree(
    graph: nx.Graph,
    request: MultipartiteRequest,
    tree: nx.Graph,
    tree_id: int,
    p_op: float = 0.8,
    q_swap: float = 1.0,
    q_fus: float = 1.0,
    q_rem: float = 1.0,
    weight_attr: str = "length_km",
) -> CandidateTree:
    rebuilt = nx.Graph()
    rebuilt.add_nodes_from(tree.nodes(data=True))
    for u, v in tree.edges():
        if graph.has_edge(u, v):
            rebuilt.add_edge(u, v, **graph[u][v])
        else:
            rebuilt.add_edge(u, v, **tree[u][v])

    plan = build_tree_operation_plan(
        rebuilt,
        users=request.terminals,
        p_op=p_op,
        q_swap=q_swap,
        q_fus=q_fus,
        q_rem=q_rem,
        weight_attr=weight_attr,
    )
    memory = compute_tree_memory(rebuilt, request.terminals, memory_model="degree")

    return CandidateTree(
        tree_id=tree_id,
        request_id=request.request_id,
        terminals=list(request.terminals),
        graph=rebuilt,
        edges=sorted(norm_edge(u, v) for u, v in rebuilt.edges()),
        swap_nodes=list(plan.swap_nodes),
        fusion_nodes=list(plan.fusion_nodes),
        memory=memory,
        rho=plan.rho,
        reduced_edges=sorted(norm_edge(u, v) for u, v in plan.reduced_tree.edges()),
        removal_nodes=list(plan.candidate_removal_nodes),
    )


def build_initial_columns(
    graph: nx.Graph,
    requests: List[MultipartiteRequest],
    k_initial_trees: int = 2,
    p_op: float = 0.8,
    q_swap: float = 1.0,
    q_fus: float = 1.0,
    q_rem: float = 1.0,
    seed: Optional[int] = None,
) -> Dict[int, List[CandidateTree]]:
    return build_candidate_trees_for_requests(
        graph=graph,
        requests=requests,
        k_trees_per_request=k_initial_trees,
        p_op=p_op,
        q_swap=q_swap,
        q_fus=q_fus,
        q_rem=q_rem,
        rho_min=0.0,
        weight_attr="length_km",
        seed=seed,
    )


def solve_restricted_master_lp(
    graph: nx.Graph,
    requests: List[MultipartiteRequest],
    candidate_trees: Dict[int, List[CandidateTree]],
    source_budget: int,
    max_sources_per_edge: int = 5,
    node_memory: Optional[Dict[Any, int]] = None,
    source_cost: int = 1,
    max_trees_per_request: int = 1,
    solver_seed: Optional[int] = None,
    verbose: bool = False,
) -> RMPResult:
    edges = sorted(norm_edge(u, v) for u, v in graph.edges())
    nodes = sorted(graph.nodes())
    if node_memory is None:
        node_memory = {v: 10**6 for v in nodes}
    max_trees_per_request = max(1, int(max_trees_per_request))

    model = gp.Model("cg_restricted_master_lp")
    if not verbose:
        model.Params.OutputFlag = 0
    if solver_seed is not None:
        model.Params.Seed = int(solver_seed) % GUROBI_SEED_MAX

    x = {}
    y = {}
    z = {
        edge: model.addVar(
            lb=0.0,
            ub=max_sources_per_edge,
            vtype=GRB.CONTINUOUS,
            name=f"z_{edge[0]}_{edge[1]}",
        )
        for edge in edges
    }
    for req in requests:
        y[req.request_id] = model.addVar(
            lb=0.0,
            ub=1.0,
            vtype=GRB.CONTINUOUS,
            name=f"y_r{req.request_id}",
        )
        for tree in candidate_trees.get(req.request_id, []):
            x[(req.request_id, tree.tree_id)] = model.addVar(
                lb=0.0,
                ub=1.0,
                vtype=GRB.CONTINUOUS,
                name=f"x_r{req.request_id}_t{tree.tree_id}",
            )
    model.update()

    objective_mode = ilp_objective_mode()
    if objective_mode not in {
        "expected_throughput",
        "coverage_expected_throughput",
        "coverage_expected_throughput_with_redundancy",
    }:
        raise ValueError(f"Unsupported ILP objective_mode={objective_mode!r}.")

    coverage_terms = []
    if objective_mode in {
        "coverage_expected_throughput",
        "coverage_expected_throughput_with_redundancy",
    }:
        coverage_weight = served_request_priority(candidate_trees)
        coverage_terms = [
            coverage_weight * y[req.request_id]
            for req in requests
        ]

    # The RMP uses expected tree utility w_r * rho_{r,t}. Actual Bernoulli
    # link, swap, and fusion outcomes are sampled later by the simulator.
    expected_terms = [
        tree_expected_throughput_value(req, tree) * x[(req.request_id, tree.tree_id)]
        for req in requests
        for tree in candidate_trees.get(req.request_id, [])
    ]
    model.setObjective(
        gp.quicksum(coverage_terms + expected_terms),
        GRB.MAXIMIZE,
    )

    request_lower_constraints = {}
    request_upper_constraints = {}
    for req in requests:
        selected_for_request = gp.quicksum(
            x[(req.request_id, tree.tree_id)]
            for tree in candidate_trees.get(req.request_id, [])
        )
        request_lower_constraints[req.request_id] = model.addConstr(
            y[req.request_id] - selected_for_request <= 0,
            name=f"request_coverage_lower_r{req.request_id}",
        )
        request_upper_constraints[req.request_id] = model.addConstr(
            selected_for_request - max_trees_per_request * y[req.request_id] <= 0,
            name=f"request_tree_limit_r{req.request_id}",
        )

    edge_constraints = {}
    edge_exact_constraints = {}
    for edge in edges:
        selected_edge_load = gp.quicksum(
                x[(req.request_id, tree.tree_id)]
                for req in requests
                for tree in candidate_trees.get(req.request_id, [])
                if edge in tree.edges
            )
        edge_constraints[edge] = model.addConstr(
            selected_edge_load - z[edge] <= 0,
            name=f"edge_source_capacity_{edge[0]}_{edge[1]}",
        )
        edge_exact_constraints[edge] = model.addConstr(
            z[edge] - selected_edge_load <= 0,
            name=f"edge_source_exact_without_redundancy_{edge[0]}_{edge[1]}",
        )

    budget_constraint = model.addConstr(
        gp.quicksum(
            source_cost * z[edge]
            for edge in edges
        )
        <= source_budget,
        name="source_budget",
    )

    memory_constraints = {}
    source_memory_constraints = {}
    for node in nodes:
        memory_constraints[node] = model.addConstr(
            gp.quicksum(
                tree.memory.get(node, 0) * x[(req.request_id, tree.tree_id)]
                for req in requests
                for tree in candidate_trees.get(req.request_id, [])
            )
            <= int(node_memory.get(node, 0)),
            name=f"memory_{node}",
        )
        source_memory_constraints[node] = model.addConstr(
            gp.quicksum(
                z[edge]
                for edge in edges
                if node in edge
            )
            <= int(node_memory.get(node, 0)),
            name=f"memory_source_placement_{node}",
        )

    model.optimize()

    status = model.Status
    if status not in [GRB.OPTIMAL, GRB.SUBOPTIMAL]:
        return RMPResult(
            status=status,
            status_name=status_to_string(status),
            objective=0.0,
            request_duals={},
            request_lower_duals={},
            request_upper_duals={},
            edge_duals={},
            edge_exact_duals={},
            budget_dual=0.0,
            memory_duals={},
            source_memory_duals={},
            objective_mode=objective_mode,
            model=model,
        )

    request_lower_duals = {
        req_id: float(constr.Pi) for req_id, constr in request_lower_constraints.items()
    }
    request_upper_duals = {
        req_id: float(constr.Pi) for req_id, constr in request_upper_constraints.items()
    }
    return RMPResult(
        status=status,
        status_name=status_to_string(status),
        objective=float(model.ObjVal),
        request_duals=request_upper_duals,
        request_lower_duals=request_lower_duals,
        request_upper_duals=request_upper_duals,
        edge_duals={edge: float(constr.Pi) for edge, constr in edge_constraints.items()},
        edge_exact_duals={edge: float(constr.Pi) for edge, constr in edge_exact_constraints.items()},
        budget_dual=float(budget_constraint.Pi),
        memory_duals={
            node: float(constr.Pi) for node, constr in memory_constraints.items()
        },
        source_memory_duals={
            node: float(constr.Pi) for node, constr in source_memory_constraints.items()
        },
        objective_mode=objective_mode,
        model=model,
    )


def reduced_profit(
    request: MultipartiteRequest,
    tree: CandidateTree,
    request_lower_dual: float,
    request_upper_dual: float,
    edge_duals: Dict[Edge, float],
    edge_exact_duals: Dict[Edge, float],
    budget_dual: float,
    memory_duals: Dict[Any, float],
    source_cost: int = 1,
) -> float:
    del budget_dual, source_cost
    edge_cost = sum(
        edge_duals.get(edge, 0.0) - edge_exact_duals.get(edge, 0.0)
        for edge in tree.edges
    )
    memory_cost = sum(
        memory_duals.get(node, 0.0) * amount for node, amount in tree.memory.items()
    )
    # RMP request constraints are written as:
    #   y_r - sum_t x_{r,t} <= 0
    #   sum_t x_{r,t} - D_r y_r <= 0
    # so an x-column has coefficients -1 and +1 in those constraints.
    request_dual_cost = request_upper_dual - request_lower_dual
    expected_value = tree_expected_throughput_value(request, tree)
    return float(expected_value - request_dual_cost - edge_cost - memory_cost)


def build_pricing_graph(
    graph: nx.Graph,
    edge_duals: Dict[Edge, float],
    budget_dual: float,
    memory_duals: Dict[Any, float],
    source_cost: int = 1,
    jitter: float = 0.0,
    rng_seed: Optional[int] = None,
) -> nx.Graph:
    set_global_seed(rng_seed)
    rng = __import__("random")

    priced = nx.Graph()
    priced.add_nodes_from(graph.nodes(data=True))
    for u, v, data in graph.edges(data=True):
        edge = norm_edge(u, v)
        weight = (
            budget_dual * source_cost
            + edge_duals.get(edge, 0.0)
            + memory_duals.get(u, 0.0)
            + memory_duals.get(v, 0.0)
        )
        if jitter > 0:
            weight *= 1.0 + jitter * rng.random()
        weight = max(float(weight), 1e-9)

        attrs = dict(data)
        attrs["pricing_weight"] = weight
        priced.add_edge(u, v, **attrs)
    return priced


def price_request_columns(
    graph: nx.Graph,
    request: MultipartiteRequest,
    rmp_result: RMPResult,
    existing_signatures: set,
    start_tree_id: int,
    source_cost: int = 1,
    p_op: float = 0.8,
    q_swap: float = 1.0,
    q_fus: float = 1.0,
    q_rem: float = 1.0,
    pricing_trials: int = 3,
    max_columns_to_add: int = 1,
    reduced_profit_tol: float = 1e-6,
    seed: Optional[int] = None,
) -> List[PricingResult]:
    results: List[PricingResult] = []
    request_lower_dual = rmp_result.request_lower_duals.get(request.request_id, 0.0)
    request_upper_dual = rmp_result.request_upper_duals.get(request.request_id, 0.0)
    next_id = start_tree_id
    added_count = 0
    max_columns_to_add = max(1, int(max_columns_to_add))

    for trial in range(pricing_trials):
        pricing_graph = build_pricing_graph(
            graph=graph,
            edge_duals=rmp_result.edge_duals,
            budget_dual=rmp_result.budget_dual,
            memory_duals=rmp_result.memory_duals,
            source_cost=source_cost,
            jitter=0.02 if trial > 0 else 0.0,
            rng_seed=derive_seed(seed, "pricing-graph", request.request_id, trial),
        )

        try:
            tree = approximate_steiner_tree(
                pricing_graph,
                request.terminals,
                weight_key="pricing_weight",
            )
        except nx.NetworkXException:
            continue

        signature = tree_signature(tree)
        if signature in existing_signatures:
            continue

        candidate = candidate_from_tree(
            graph=graph,
            request=request,
            tree=tree,
            tree_id=next_id,
            p_op=p_op,
            q_swap=q_swap,
            q_fus=q_fus,
            q_rem=q_rem,
        )
        profit = reduced_profit(
            request,
            candidate,
            request_lower_dual=request_lower_dual,
            request_upper_dual=request_upper_dual,
            edge_duals=rmp_result.edge_duals,
            edge_exact_duals=rmp_result.edge_exact_duals,
            budget_dual=rmp_result.budget_dual,
            memory_duals=rmp_result.memory_duals,
            source_cost=source_cost,
        )
        added = profit > reduced_profit_tol
        results.append(
            PricingResult(
                request_id=request.request_id,
                candidate=candidate if added else None,
                reduced_profit=profit,
                added=added,
            )
        )
        if added:
            existing_signatures.add(signature)
            next_id += 1
            added_count += 1
            if added_count >= max_columns_to_add:
                break

    return results


def price_request_columns_from_pool(
    request: MultipartiteRequest,
    pool_trees: List[CandidateTree],
    rmp_result: RMPResult,
    existing_signatures: set,
    max_columns_to_add: int = 1,
    reduced_profit_tol: float = 1e-6,
    source_cost: int = 1,
) -> List[PricingResult]:
    """
    Exact reduced-profit pricing over a finite candidate pool.

    This is not a proof of global optimality over all possible Steiner trees.
    It is exact over the same finite candidate-tree universe generated for the
    ILP family, which makes ILP-CG easier to audit and compare.
    """
    request_lower_dual = rmp_result.request_lower_duals.get(request.request_id, 0.0)
    request_upper_dual = rmp_result.request_upper_duals.get(request.request_id, 0.0)
    scored: List[Tuple[float, CandidateTree]] = []
    for candidate in pool_trees:
        signature = frozenset(candidate.edges)
        if signature in existing_signatures:
            continue
        profit = reduced_profit(
            request,
            candidate,
            request_lower_dual=request_lower_dual,
            request_upper_dual=request_upper_dual,
            edge_duals=rmp_result.edge_duals,
            edge_exact_duals=rmp_result.edge_exact_duals,
            budget_dual=rmp_result.budget_dual,
            memory_duals=rmp_result.memory_duals,
            source_cost=source_cost,
        )
        scored.append((profit, candidate))

    scored.sort(
        key=lambda item: (
            -item[0],
            len(item[1].edges),
            -item[1].rho,
            item[1].tree_id,
        )
    )
    results: List[PricingResult] = []
    added_count = 0
    max_columns_to_add = max(1, int(max_columns_to_add))
    for profit, candidate in scored:
        added = profit > reduced_profit_tol
        results.append(
            PricingResult(
                request_id=request.request_id,
                candidate=candidate if added else None,
                reduced_profit=profit,
                added=added,
            )
        )
        if not added:
            break
        existing_signatures.add(frozenset(candidate.edges))
        added_count += 1
        if added_count >= max_columns_to_add:
            break

    return results


def cg_pricing_mode() -> str:
    try:
        import single_slot_throughput_sweep_conditions as conditions

        return str(getattr(conditions, "ILP_CG_PRICING_MODE", "candidate_pool_exact"))
    except (ImportError, AttributeError):
        return "candidate_pool_exact"


def cg_pricing_pool_tree_count(default: int) -> int:
    try:
        import single_slot_throughput_sweep_conditions as conditions

        return max(1, int(getattr(conditions, "ILP_CG_PRICING_POOL_TREES", default)))
    except (ImportError, AttributeError):
        return max(1, int(default))


def column_generation_source_placement(
    graph: nx.Graph,
    requests: List[MultipartiteRequest],
    source_budget: int,
    max_sources_per_edge: int = 5,
    node_memory: Optional[Dict[Any, int]] = None,
    source_cost: int = 1,
    k_initial_trees: int = 2,
    pricing_trials: int = 3,
    max_trees_per_request: Optional[int] = None,
    max_pricing_columns_per_request: int = 3,
    max_iterations: int = 20,
    reduced_profit_tol: float = 1e-6,
    p_op: float = 0.8,
    q_swap: float = 1.0,
    q_fus: float = 1.0,
    q_rem: float = 1.0,
    master_seed: Optional[int] = None,
    final_time_limit: Optional[float] = None,
    final_mip_gap: Optional[float] = None,
    verbose: bool = False,
) -> Dict[str, Any]:
    set_global_seed(master_seed)
    initial_seed = derive_seed(master_seed, "cg", "initial-columns")
    solver_seed = derive_seed(master_seed, "cg", "rmp-solver")
    final_solver_seed = derive_seed(master_seed, "cg", "final-ilp-solver")
    if max_trees_per_request is None:
        max_trees_per_request = max(1, int(k_initial_trees) + int(pricing_trials))
    else:
        max_trees_per_request = max(1, int(max_trees_per_request))

    pricing_mode = cg_pricing_mode()
    pricing_pool: Optional[Dict[int, List[CandidateTree]]] = None
    if pricing_mode == "candidate_pool_exact":
        pool_tree_count = cg_pricing_pool_tree_count(
            max(int(k_initial_trees), int(max_trees_per_request), int(pricing_trials))
        )
        pool_seed = derive_seed(master_seed, "ilp", "candidate-trees")
        pricing_pool = build_candidate_trees_for_requests(
            graph=graph,
            requests=requests,
            k_trees_per_request=pool_tree_count,
            p_op=p_op,
            q_swap=q_swap,
            q_fus=q_fus,
            q_rem=q_rem,
            rho_min=0.0,
            weight_attr="length_km",
            seed=pool_seed,
        )
        candidate_trees = {
            req.request_id: list(pricing_pool.get(req.request_id, [])[: max(1, int(k_initial_trees))])
            for req in requests
        }
        initial_seed = pool_seed
    elif pricing_mode == "heuristic_steiner":
        pool_tree_count = 0
        pool_seed = None
        candidate_trees = build_initial_columns(
            graph=graph,
            requests=requests,
            k_initial_trees=k_initial_trees,
            p_op=p_op,
            q_swap=q_swap,
            q_fus=q_fus,
            q_rem=q_rem,
            seed=initial_seed,
        )
    else:
        raise ValueError(
            "Unsupported ILP_CG_PRICING_MODE="
            f"{pricing_mode!r}; expected 'candidate_pool_exact' or 'heuristic_steiner'."
        )

    signatures = {
        req.request_id: {frozenset(tree.edges) for tree in candidate_trees.get(req.request_id, [])}
        for req in requests
    }

    rmp_history = []
    pricing_history = []
    total_added = 0

    for iteration in range(max_iterations):
        rmp_result = solve_restricted_master_lp(
            graph=graph,
            requests=requests,
            candidate_trees=candidate_trees,
            source_budget=source_budget,
            max_sources_per_edge=max_sources_per_edge,
            node_memory=node_memory,
            source_cost=source_cost,
            max_trees_per_request=max_trees_per_request,
            solver_seed=derive_seed(solver_seed, "iteration", iteration),
            verbose=verbose,
        )
        rmp_history.append(
            {
                "iteration": iteration,
                "status": rmp_result.status_name,
                "objective": rmp_result.objective,
                "num_columns": sum(len(v) for v in candidate_trees.values()),
            }
        )

        if rmp_result.status_name not in {"OPTIMAL", "SUBOPTIMAL"}:
            break

        added_this_iteration = 0
        next_id = next_tree_id(candidate_trees)
        for req in requests:
            if pricing_mode == "candidate_pool_exact":
                pricing_results = price_request_columns_from_pool(
                    request=req,
                    pool_trees=list((pricing_pool or {}).get(req.request_id, [])),
                    rmp_result=rmp_result,
                    existing_signatures=signatures.setdefault(req.request_id, set()),
                    max_columns_to_add=max_pricing_columns_per_request,
                    reduced_profit_tol=reduced_profit_tol,
                    source_cost=source_cost,
                )
            else:
                pricing_results = price_request_columns(
                    graph=graph,
                    request=req,
                    rmp_result=rmp_result,
                    existing_signatures=signatures.setdefault(req.request_id, set()),
                    start_tree_id=next_id,
                    source_cost=source_cost,
                    p_op=p_op,
                    q_swap=q_swap,
                    q_fus=q_fus,
                    q_rem=q_rem,
                    pricing_trials=pricing_trials,
                    max_columns_to_add=max_pricing_columns_per_request,
                    reduced_profit_tol=reduced_profit_tol,
                    seed=derive_seed(master_seed, "cg", "pricing", iteration),
                )
            pricing_history.extend(
                {
                    "iteration": iteration,
                    "request_id": item.request_id,
                    "reduced_profit": item.reduced_profit,
                    "added": item.added,
                    "pricing_mode": pricing_mode,
                }
                for item in pricing_results
            )

            for item in pricing_results:
                if item.added and item.candidate is not None:
                    candidate_trees.setdefault(req.request_id, []).append(item.candidate)
                    next_id = max(next_id, item.candidate.tree_id + 1)
                    added_this_iteration += 1
                    total_added += 1

        if verbose:
            print(
                f"[CG] iter={iteration}, RMP={rmp_result.objective:.6f}, "
                f"added={added_this_iteration}"
            )

        if added_this_iteration == 0:
            break

    final_result = solve_joint_source_placement_ilp(
        graph=graph,
        requests=requests,
        candidate_trees=candidate_trees,
        source_budget=source_budget,
        max_sources_per_edge=max_sources_per_edge,
        node_memory=node_memory,
        source_cost=source_cost,
        allow_multiple_trees_per_request=True,
        demand_per_request=max_trees_per_request,
        time_limit=final_time_limit,
        mip_gap=final_mip_gap,
        solver_seed=None if final_solver_seed is None else int(final_solver_seed) % GUROBI_SEED_MAX,
        verbose=verbose,
    )

    final_result["cg_candidate_trees"] = candidate_trees
    final_result["cg_iterations"] = len(rmp_history)
    final_result["cg_added_columns"] = total_added
    final_result["cg_rmp_history"] = rmp_history
    final_result["cg_pricing_history"] = pricing_history
    final_result["cg_pricing_mode"] = pricing_mode
    final_result["cg_pricing_pool_trees"] = pool_tree_count
    final_result["cg_pricing_pool_seed"] = pool_seed
    final_result["cg_initial_seed"] = initial_seed
    final_result["cg_final_solver_seed"] = final_solver_seed
    final_result["cg_max_trees_per_request"] = max_trees_per_request
    final_result["cg_max_pricing_columns_per_request"] = max_pricing_columns_per_request
    final_result["candidate_tree_counts"] = {
        req_id: len(trees) for req_id, trees in candidate_trees.items()
    }
    return final_result


def solve_single_slot_ilp_cg_request_batch(
    edge_list: List[tuple],
    request_batch: Iterable[Iterable[Any]],
    source_budget: int,
    max_sources_per_edge: int = 5,
    node_memory: Optional[Dict[Any, int]] = None,
    node_memory_capacity: Optional[int] = None,
    k_initial_trees: int = 2,
    pricing_trials: int = 3,
    max_trees_per_request: Optional[int] = None,
    max_pricing_columns_per_request: int = 3,
    max_iterations: int = 20,
    p_op: float = 0.8,
    q_swap: float = 1.0,
    q_fus: float = 1.0,
    q_rem: float = 1.0,
    master_seed: Optional[int] = None,
    final_time_limit: Optional[float] = None,
    final_mip_gap: Optional[float] = None,
    verbose: bool = False,
) -> Dict[str, Any]:
    topo = Topology(edge_list)
    graph = topo.graph
    requests = requests_from_user_sets(request_batch)

    if node_memory is None and node_memory_capacity is not None:
        node_memory = {v: int(node_memory_capacity) for v in topo.get_nodes()}

    use_nested_pool = False
    try:
        import single_slot_throughput_sweep_conditions as conditions

        use_nested_pool = bool(getattr(conditions, "ILP_CG_USE_NESTED_POOL", False))
    except (ImportError, AttributeError):
        use_nested_pool = False

    if use_nested_pool:
        nested_max_trees = max(1, int(max_trees_per_request or k_initial_trees))
        candidate_seed = derive_seed(master_seed, "ilp", "candidate-trees")
        solver_seed = derive_seed(master_seed, "cg", "nested-final-ilp-solver")
        candidate_trees = build_candidate_trees_for_requests(
            graph=graph,
            requests=requests,
            k_trees_per_request=nested_max_trees,
            p_op=p_op,
            q_swap=q_swap,
            q_fus=q_fus,
            q_rem=q_rem,
            rho_min=0.0,
            weight_attr="length_km",
            seed=candidate_seed,
        )

        result = solve_joint_source_placement_ilp(
            graph=graph,
            requests=requests,
            candidate_trees=candidate_trees,
            source_budget=source_budget,
            max_sources_per_edge=max_sources_per_edge,
            node_memory=node_memory,
            source_cost=1,
            allow_multiple_trees_per_request=True,
            demand_per_request=nested_max_trees,
            time_limit=final_time_limit,
            mip_gap=final_mip_gap,
            solver_seed=None if solver_seed is None else int(solver_seed) % GUROBI_SEED_MAX,
            verbose=verbose,
        )
        result["cg_candidate_trees"] = candidate_trees
        result["cg_iterations"] = 0
        result["cg_added_columns"] = 0
        result["cg_rmp_history"] = []
        result["cg_pricing_history"] = []
        result["cg_initial_seed"] = candidate_seed
        result["cg_final_solver_seed"] = solver_seed
        result["cg_max_trees_per_request"] = nested_max_trees
        result["cg_max_pricing_columns_per_request"] = 0
        result["cg_nested_pool"] = True
        result["candidate_tree_counts"] = {
            req_id: len(trees) for req_id, trees in candidate_trees.items()
        }
        result["throughput_selected_trees"] = len(result["selected_trees"])
        result["throughput_covered_requests"] = len(result.get("covered_requests", result["served_requests"]))
        result["throughput_qbps"] = result["throughput_covered_requests"]
        result["ilp_expected_objective"] = result.get("ilp_expected_objective", result["objective"] or 0.0)
        result["ilp_expected_throughput_term"] = result.get("ilp_expected_throughput_term", 0.0)
        result["ilp_covered_requests"] = result.get("ilp_covered_requests", result["throughput_covered_requests"])
        result["ilp_selected_tree_count"] = result.get("ilp_selected_tree_count", result["throughput_selected_trees"])
        result["deployed_source_count"] = result.get(
            "deployed_source_count",
            sum(result.get("routing_source_placement", {}).values()),
        )
        result["request_batch"] = [list(req) for req in request_batch]
        result["master_seed"] = master_seed
        return result

    result = column_generation_source_placement(
        graph=graph,
        requests=requests,
        source_budget=source_budget,
        max_sources_per_edge=max_sources_per_edge,
        node_memory=node_memory,
        source_cost=1,
        k_initial_trees=k_initial_trees,
        pricing_trials=pricing_trials,
        max_trees_per_request=max_trees_per_request,
        max_pricing_columns_per_request=max_pricing_columns_per_request,
        max_iterations=max_iterations,
        p_op=p_op,
        q_swap=q_swap,
        q_fus=q_fus,
        q_rem=q_rem,
        master_seed=master_seed,
        final_time_limit=final_time_limit,
        final_mip_gap=final_mip_gap,
        verbose=verbose,
    )

    result["throughput_selected_trees"] = len(result["selected_trees"])
    result["throughput_covered_requests"] = len(result.get("covered_requests", result["served_requests"]))
    result["throughput_qbps"] = result["throughput_covered_requests"]
    result["ilp_expected_objective"] = result.get("ilp_expected_objective", result["objective"] or 0.0)
    result["ilp_expected_throughput_term"] = result.get("ilp_expected_throughput_term", 0.0)
    result["ilp_covered_requests"] = result.get("ilp_covered_requests", result["throughput_covered_requests"])
    result["ilp_selected_tree_count"] = result.get("ilp_selected_tree_count", result["throughput_selected_trees"])
    result["deployed_source_count"] = result.get(
        "deployed_source_count",
        sum(result.get("routing_source_placement", {}).values()),
    )
    result["request_batch"] = [list(req) for req in request_batch]
    result["master_seed"] = master_seed
    return result


def main() -> None:
    import single_slot_throughput_sweep_conditions as conditions

    edge_list = [
        (0, 1, 0),
        (1, 2, 0),
        (0, 3, 0),
        (3, 4, 0),
        (2, 4, 0),
        (1, 3, 0),
    ]
    request_batch = [[0, 2, 4], [0, 1, 3]]
    result = solve_single_slot_ilp_cg_request_batch(
        edge_list=edge_list,
        request_batch=request_batch,
        source_budget=20,
        max_sources_per_edge=4,
        k_initial_trees=1,
        pricing_trials=3,
        max_iterations=5,
        p_op=1.0,
        master_seed=conditions.RANDOM_SEED,
        final_time_limit=10,
        final_mip_gap=0.01,
        verbose=False,
    )
    assert result["status_name"] in {"OPTIMAL", "TIME_LIMIT", "SUBOPTIMAL"}
    assert "routing_source_placement" in result
    print("Column generation ILP test passed.")
    print(f"Status: {result['status_name']}")
    print(f"ILP-CG expected objective: {result.get('ilp_expected_objective', result['objective'])}")
    print(f"CG iterations: {result['cg_iterations']}")
    print(f"Added columns: {result['cg_added_columns']}")
    print(f"Routing source placement: {result['routing_source_placement']}")


if __name__ == "__main__":
    main()
